flags: {}
nix:
  shell-file: shell.nix
packages:
- yi-core
- yi-dynamic-configuration
- yi-frontend-vty
# - yi-frontend-pango
- yi-fuzzy-open
- yi-keymap-cua
- yi-keymap-emacs
- yi-keymap-vim
- yi-mode-haskell
- yi-mode-javascript
- yi-misc-modes
- yi-intero
- yi-ireader
- yi-language
- yi-snippet
- yi
resolver: lts-18.3
extra-deps:
- Hclip-3.0.0.4@sha256:df341c936594465df25c3b9f93f6ebe3110a36d64a51dbbd1dbd557394bbdba4,1648
build:
 library-profiling: false
 executable-profiling: false

# needed for macOS
# flags:
#   gtk:
#     have-quartz-gtk: true
